language: node_js
node_js:
  - 8
before_install:
  - cd packages/react-scripts/
  - node custom/travis/beforeInstall
before_deploy:
  - export DEPLOY_TAG=$(node custom/travis/beforeDeploy)
deploy:
  tag: $DEPLOY_TAG
  provider: npm
  email: ackeedevelopment@gmail.com
  skip_cleanup: true
  api_key:
    secure: Ep+Mj5Ly5UP0b94g6NIyvyBf52bXBL4TvZ3xwqmzs0yAcb5yukZDf/+zrB5t8M6Aw1AnAajHvbf0DmzviXtcCUKsvgF2gjZrx64dVcRuMRUEdQVxoJsYNUwppocmySbeHnc/k0xradO1VEhd91sfOffryp8fhyMyMBQ+mqOCabsdVJqiKAkACFY/rSZ5NPRgmuofzAXPjMLDzalfiyweXyIBzsflACJSQeDWFx4fJqT6vAHAQd6LCuUQya21/AQ4ylRcAL2Gtn0KPstqIWlT7lhHhjPD/4pLX7dCu8PZ6lsu2sgkN7XhdZejjWOZ3wgtAWR6UY46eGVLqVyJLMtz4xlGf2CenCIa283eUvN7P1+1s3ckix4qLP3o2nyCcN8vqm2Dd4ZRQiYixHEl+Nq88tglYYL52gGaDmbMIwXvp6pkAupeJx8ZW/b3AFzQ5Zc+L1TjvJ1UtIQgMDvCwobnv7y/91mdyUTSMFpYwYlPGQIUzbhBAd2jrrvvbxYTwv2g1eqHbrWlQ3vR/o6vkmYd4Xxg2tS8N2sOprLdph8jBo3wd5ddIJS+IscHQBgzhXke5woBgg6k6gjET+E33qP/po8dzQByTXSMBlU+fwEcxlLzIlQ71Q0mIrtMqawZPAYDh4bmrSTPTExlXuZWH5PpOp0JLlJCeaxjRGGmtDVAttE=
  on:
    tags: true
    repo: AckeeCZ/create-react-app
