language: node_js
node_js:
  - 12
before_install:
  - cd packages/react-scripts/
  - node custom/travis/beforeInstall
before_deploy:
  - export DEPLOY_TAG=$(node custom/travis/beforeDeploy)
before_script:
  - npm install -g npm@latest
deploy:
  tag: '$DEPLOY_TAG'
  provider: npm
  email: ackeedevelopment@gmail.com
  skip_cleanup: true
  api_key:
    secure: SE1MCqDpcbALu79vVfsKjvNIYe3bsLMFg0WsaHCT4suh7ClACUPWCJkakCM+J2H5O2NguthDgrOby7sZZqF9P6bz9ihflUCVEIE5Ylm9GIAl639cvQWGv9bObMFATmrrdbP7WEmx6o3+LattLJAUgZPBldDXuDdaoJ/C3+0GmDRVIavfFsqxHJf0oCanwTpJty283DrwQMsUgy0rpRhHY8to8S65sAkTKFAXIf1L8QLJ2fcnTtDS5Gr1XQtukz+UYJYHqgJhmULECLJT707tg4HLPVwfIJKk6I2okevodx9iK1+wID0b6sZ2zR5IWSpJsOsQJypIXEEt+0yzBhPYg3+uOAtox5kMksmYciLj9IklEf3DmD56V3Tbz3jlEaJOGDlknTsMge0mpFjlrLKade2incO9mkWn3CC9nzA/ldtU1MWvixij6+xTcDL5dHIdFrPDlNTuWPiRseK+c95YDjozHRoD4NTcqEOqpR3GlsTWkUpWMZXmg9vHid/Qwnr4s2JDugU0G5esSR/iraDtymlV3Wwl/ax2S47W7IYwtBdETilE2HRp1eYqav2vhhxxa5LV7820W/CF/O4L4UNGpIUQjlD1keMsO2mjCnQV6jgAXqprdHfXqyJ5OdAljKLZpCZS7vpBNTnXr0MXTyExLSUHx74s/PPN5Wvv2TSAsJs=
  on:
    tags: true
    repo: AckeeCZ/create-react-app
